service:
  id: 1
  name: golang-clean-architecture
  version: 1.0.0
  logger:
    level: info
    mode: development
    encoder: console
  grpc:
    port: :5001
    development: true
  http:
    host: localhost
    port: 5007
    basePath: /api/v1
    bankAccountsPath: /api/v1/accounts
    debugErrorsResponse: true
    ignoreLogUrls: [ "metrics", "swagger" ]

postgres:
  url: host=localhost user=admin password=admin dbname=gorm port=5432 sslmode=disable TimeZone=Asia/Shanghai

redis:
  url: localhost:6379
  queues:
    orders: orders