service:
  id: 1
  name: golang-clean-architecture
  version: 1.0.0
  http:
    mode: debug # debug, release or test
    host: localhost
    port: 8080
  logger:
    level: info # debug, info, warn, error, dPanic, panic or fatal
    mode: development # development or production
    encoder: console # console or json

postgres:
  host: localhost
  port: 5432
  user: admin
  password: admin
  databaseName: gorm
  sslMode: disable # enable or disable
  timeZone: Asia/Tehran

redis:
  url: localhost:6379
  queues:
    orders: orders