version: '3.9'

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend


  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - backend


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - backend


  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "9251:8081"
    depends_on:
      - redis
    networks:
      - backend


  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    volumes:
      - jaeger:/tmp
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    networks:
      - backend

networks:
  backend:

volumes:
  postgresql:
  pgadmin:
  redis:
  jaeger:
